### PR TITLE
First version of the extension options page

### PR DESCRIPTION
**Pull request by whiver**
First PR for the implementation of #477.
I'm here adding an option page to the extension that will allow the user to define default password options. To reduce to size of the PR, the scope of this first iteration is limited:

- No styling
- No UTs
- Only default login can be set in the options

As the scope of this PR is limited, the option page is not available yet. To test it, set the v-if of the item menu to true in `Menu.vue`.

I will implement the remaining features in the next PRs, see #477 for details.

I'm new to Vue, so I tried my best to do something as clean as possible, but feel free to add comments if needed :)

### Demo
Peek 15-10-2019 20-20

### CODE REVIEW

**Comment by guillaumevincent** [comment]
Nice!
Could you remove the changes in packages/lesspass-pure/dist/ folder?
The CI will build the application for us.

> I'm new to Vue, so I tried my best to do something as clean as possible, but feel free to add comments if needed :)

For somebody new to vue it's a pretty good pull request

**Comment by whiver** [comment]
Thanks for the feedback! ☺
I reverted `lesspass-pure/dist` but also `lesspass-webextension/extension/dist` as I guess it will be generated too.

**Comment by guillaumevincent** [comment]
Yeah, I think you forgot also  packages/lesspass-web-extension/extension/dist/options.js

I'm wondering if the option page should not be inside lesspass-pure instead of inside the web extension.
An option page here: https://github.com/lesspass/lesspass/tree/master/packages/lesspass-pure/src/views

 wdyt?

Like that we will have the option for the web site, and other browser also

**Comment by whiver** [comment]
Makes sense, but it means that the option view won't be in the option page of the extension, but directly in the popup, right?

**Comment by guillaumevincent** [comment]
Exactly, this is perfect, I will merge this

**Comment by guillaumevincent** [comment]
Thank you @whiver

**Comment by whiver** [comment]
Thanks for accepting these changes! :blush:

**Pull request merged**
