### PR TITLE
Adding Polish translation

### PR DESCRIPTION
**Pull request by kocio-pl**
This is my translation into Polish. I hope adding this file is all that is needed for this change to work. If there are some other changes to be done, please let me know.

### CODE REVIEW

**Comment by kocio-pl** [comment]
It looks like translations are defined in these files, so I should probably add the new one there (to `languagesAvailable`/`LANGUAGES_AVAILABLE`):

- https://github.com/lesspass/lesspass/blob/master/packages/lesspass-pure/scripts/buildI18n.js
- https://github.com/lesspass/lesspass/blob/master/packages/lesspass-pure/src/main.js

How could I build my own web extension from the repo to test it? I guess some basic instructions in `CONTRIBUTING.md` would be helpful.

**Comment by guillaumevincent** [comment]
Thanks for this translation. 
To test this:
Add `pl` in languagesAvailable in main.js and in LANGUAGES_AVAILABLE in buildI18n.js
Run `npm run build:i18n`
Test it with your browser after running `npm start`.
Change default language in your browser and refresh the page

**Comment by kocio-pl** [comment]
I've tried in `lesspass/packages/lesspass-pure` and some modules were missing, so I installed them manually:

```bash
npm install walk vue-polyglot-utils
```

After that it goes without warnings. Then I went to `lesspass/packages/lesspass-web-extension` and did:

```bash
npm run build
```

The `gulp` was missing, so I did (probably only one is needed):

```bash
sudo apt install gulp
npm install gulp
```

and now it goes OK, so I did:

```bash
npm run zip
```

and now I see `lesspass.chrome-v8.0.2.zip` and `lesspass.firefox-v8.0.2.xpi` in `lesspass/packages/lesspass-web-extension/build`. I would like to test it, but from a fast scan inside XPI file it does not look to me now that polish translation is included.

Are there some things I should do in a diffeent way?

**Comment by kocio-pl** [comment]
Oh, I went back to `lesspass/packages/lesspass-pure` and did as requested:
```
npm start
```

Then in my browser I went to http://localhost:8080 and found that it's rendered in English, even if my default language is Polish. Changing default language to German did not work, also when I tried it in Chrome.

**Comment by guillaumevincent** [comment]
yes, looks like it's broken
I will look at it

**Comment by guillaumevincent** [comment]
Hello @kocio-pl,
I fixed the code.
Can you rebase this pull request on top of master?

You will need to update main.js and add:

```
import plLocales from "./i18n/pl.json";
...
Vue.locales({
  pl: plLocales
});

```

To test just run `npm run dev` and go to localhost:8000

Thanks

**Comment by kocio-pl** [comment]
I'm working on it.

I have a question however - there are currently 2 places where translations are stored:

- https://github.com/lesspass/lesspass/tree/master/packages/lesspass-pure/src/i18n
- https://github.com/lesspass/lesspass/tree/master/containers/frontend/dist/i18n

Should I update both for now? And is it possible to have just one place for all purposes?

**Comment by guillaumevincent** [comment]
Only src @kocio-pl 
https://github.com/lesspass/lesspass/tree/master/packages/lesspass-pure/src/i18n

The other is auto build

**Comment by kocio-pl** [comment]
Now I have changed this PR to a clean state. It works with translated languages I set in my browser.

However this state is not clean - `build` subdirectory is generated and is not current:

1. `npm run build:i18n` does not change anything
2. `npm run build` changes files `dist/lesspass.min.css.map` and `dist/lesspass.min.js`
3. `npm run dev` cleans `build` subdirectory

Which state do you prefer? I guess 3. makes a lot of sense.

**Comment by guillaumevincent** [comment]
@kocio-pl this pull request is fine
I will do the remaning work
Thank you

**Pull request merged**
