### PR TITLE
WIP: Migrate to vue-cli

### PR DESCRIPTION
**Pull request by AdamNiederer**
Moves the entire build system to vue-cli, including the webpack config, e2e system, unit tests, and dev server. Should make maintenance quite a bit easier.

### CODE REVIEW

**Comment by guillaumevincent** [comment]
Hello,

dist folder is required, because other modules are using lesspass-pure as a dependency (lesspass-web-extension) for example.

Javascript tests are failing

We are going to move lesspass-pure from vuejs to react
Vue cli is a waste of time IMO

Don't spend to much time on this one, feel free to close

**Comment by AdamNiederer** [comment]
Ah, I see. Would that be the lesspass-web-component workspace?

**Comment by guillaumevincent** [comment]
Yes but I'm working on it, so don't spend time on this

**Comment by AdamNiederer** [comment]
Okay, do let me know when it's available for contributions - I'd love to help improve the ux!

**Pull request closed without merging**
