### PR TITLE
Feat: Encrypt password profiles

### PR DESCRIPTION
**Pull request by biancarosa**
This PR is an attempt to implement #185.
I only changed the front-end on the lesspass-pure package, I don't really know if I need to change something for mobile versions.
I don't know a lot about Vue.JS so I made some questionable choices to implement this, so I appreciate any feedback.

If the user has no _key_ stored in their profile, we:

- Generate a random key for the user.
- Encrypt all password profiles with that key encrypted with the user's master password.
- Save that encrypted key on the state.
- Save the new random key on the user profile.
- Save the encrypted password profiles string on the datavase.

After that, we:
- Get the encrypted password profiles.
- Decrypt it and use the password model as per usual.

The front-end mostly keeps using the old _password_ model, but this model becomes useless on the backend now.
I'd love some feedback and I'll happily work on anything that I might have forgotten or that could be better. ;)

### CODE REVIEW

**Comment by guillaumevincent** [comment]
:rocket:

This is amazing, I need to take this one carefully, so I will do the review with a little more time.
Right now I can't do the review correctly.

I will try as soon as possible

But thank you !

**Comment by guillaumevincent** [comment]
Hello @biancarosa ,

I started to review this yesterday.

I think we are going to split the review for the backend and the frontend.

We are going to push the backend first.

Do you want me to do the split ?

**Comment by biancarosa** [comment]
Sorry it took me so long, I'm on it and I'll open a PR soon!

**Comment by guillaumevincent** [comment]
No worries !
Thank you very much

Should we close this one ?

I will look at the backend this week

**Pull request closed without merging**
