### PR TITLE
Feat: Add change password feature on website

### PR DESCRIPTION
**Pull request by biancarosa**
This is my very first attempt to do something so I am opening a draft PR first to see if I'm on the right path.

I'm working on #457 and I've tried to focus on adding the functionality to the website first. For this pull-request, I still have to do some tests. I was thinking of adding on other platforms in different pull-requests, if that's okay.

How do you guys handle new strings? I can add some translations on the i18n folder but I do not speak all of these languages (the strings are pretty simple, though, and I could use google translate :sweat_smile:)

I've...

1 - Added a link to a new change password route.
Screenshot from 2020-07-22 13-59-32
2 - Added a new change password component
Screenshot from 2020-07-22 13-59-59
Screenshot from 2020-07-22 14-00-23
3 - Tried to log in with my old password
Screenshot from 2020-07-22 14-02-02
4 - Logged in with my new password
Screenshot from 2020-07-22 14-02-29

### CODE REVIEW

**Comment by guillaumevincent** [comment]
I wake up so I forgot to say thank you :praise:

**Comment by guillaumevincent** [comment]
Ok I understood why you put the link on the password generator view.
I updated master and created a My Account view, can you rebase this PR on top of master and put the form in My Account view without a link ?

Thank you

**Comment by guillaumevincent** [comment]
I clean my mess after a git push --force used to remove a wrong email
You commit is here https://github.com/lesspass/lesspass/commit/730e7ae0c737d20715c54baf67ba94f9b3d60bd5

I close

Thank you for contributing to LessPass

**Comment by biancarosa** [comment]
Cool! I was sleeping so couldn't keep up with the discussion :) Tks for the fast review :+1:

**Pull request closed without merging**
