### PR TITLE
inherit internal ui/TextInput

### LINKED ISSUE #384: Master password is auto-capitalized
Hello,

When entering my master password on the Android app (version 3.1.1), the keyboard wants to start with a capital letter, which is annoying.

I think `autoCapitalize="none"` is missing here: https://github.com/lesspass/lesspass/blob/e526584d690e92beef8eb59006b5b33031f21533/packages/mobile/src/password/MasterPassword.js#L54

### PR DESCRIPTION
**Pull request by edouard-lopez**
fixes #384: Master password is auto-capitalized → lowervase

### CODE REVIEW

**Comment by guillaumevincent** [comment]
We cannot use TextInput from ui, because it's an unstyled password text input

**Comment by edouard-lopez** [comment]
I updated the PR, but both seems to use the same import and use the same styles:

### TextInput
https://github.com/lesspass/lesspass/blob/25383993ed6c112b0907f1ad6e04e2e3911d0dee/packages/lesspass-mobile/src/ui/TextInput.js#L4
https://github.com/lesspass/lesspass/blob/25383993ed6c112b0907f1ad6e04e2e3911d0dee/packages/lesspass-mobile/src/ui/TextInput.js#L14

### MasterPassword
https://github.com/lesspass/lesspass/blob/25383993ed6c112b0907f1ad6e04e2e3911d0dee/packages/lesspass-mobile/src/password/MasterPassword.js#L5
https://github.com/lesspass/lesspass/blob/25383993ed6c112b0907f1ad6e04e2e3911d0dee/packages/lesspass-mobile/src/password/MasterPassword.js#L55

**Comment by guillaumevincent** [comment]
hum let me try, you are probably right

**Comment by guillaumevincent** [comment]
Because of symlink issue with yarn workspaces and react-native, I move react-native in his own folder out of yarn workspaces see https://github.com/lesspass/lesspass/commit/9c3794971e69fe5637da0f33721b3185b849b267

I reuse `import TextInput from "../ui/TextInput";` instead of `import { TextInput } from "../ui/TextInput";` as proposed in the first patch.
Thanks

**Pull request closed without merging**
