### PR TITLE
Update and rename packages/lesspass-pure/src/index.html to packages/l…

### PR DESCRIPTION
**Pull request by Kcchouette**
…esspass-pure/index.html

Else on the page, nothing is load, as index.html is not in the same folder of dist

### CODE REVIEW

**Comment by Kcchouette** [comment]
@guillaumevincent I'm trying to use lesspass-pure/index.html as a real page.
In the case this page is located in src/ : 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/user/lesspass/packages/lesspass-pure/dist/af7ae505a9eed503f8b8e6982036873e.woff2. (Reason: CORS request not http).

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:1): bad URI or cross-site access not allowed source: file:///home/user/lesspass/packages/lesspass-pure/dist/af7ae505a9eed503f8b8e6982036873e.woff2 unknown:7:11
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/user/lesspass/packages/lesspass-pure/dist/fee66e712a8a08eef5805a46892932ad.woff. (Reason: CORS request not http).

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:2): bad URI or cross-site access not allowed source: file:///home/user/lesspass/packages/lesspass-pure/dist/fee66e712a8a08eef5805a46892932ad.woff unknown:7:11
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/user/lesspass/packages/lesspass-pure/dist/b06871f281fee6b241d60582ae9369b9.ttf. (Reason: CORS request not http).

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:3): bad URI or cross-site access not allowed source: file:///home/user/lesspass/packages/lesspass-pure/dist/b06871f281fee6b241d60582ae9369b9.ttf unknown:7:11
downloadable font: no supported format found (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:5) source: (end of source list) unknown:7:11
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. lesspass.min.css:20:27
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. lesspass.min.css:2346:13
Unknown property ‘-moz-opacity’.  Declaration dropped. lesspass.min.css:2348:18
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. lesspass.min.css:2375:13
Unknown property ‘-moz-opacity’.  Declaration dropped. lesspass.min.css:2377:18
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. lesspass.min.css:2390:13
Unknown property ‘-moz-opacity’.  Declaration dropped. lesspass.min.css:2392:18
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. lesspass.min.css:2820:29
Unknown property ‘text-decoration-skip-ink’.  Declaration dropped. lesspass.min.css:2858:28
Error in parsing value for ‘outline’.  Declaration dropped. lesspass.min.css:2969:20
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. lesspass.min.css:4050:17
Unknown pseudo-class or pseudo-element ‘-ms-value’.  Ruleset ignored due to bad selector. lesspass.min.css:4066:27
Unknown property ‘user-select’.  Declaration dropped. lesspass.min.css:4417:15
Unknown property ‘appearance’.  Declaration dropped. lesspass.min.css:5409:14
Unknown pseudo-class or pseudo-element ‘-ms-value’.  Ruleset ignored due to bad selector. lesspass.min.css:5414:26
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. lesspass.min.css:5424:18
Unknown property ‘appearance’.  Declaration dropped. lesspass.min.css:5500:14
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. lesspass.min.css:5507:25
Unknown property ‘appearance’.  Declaration dropped. lesspass.min.css:5519:16
Unknown pseudo-class or pseudo-element ‘active’.  Ruleset ignored due to bad selector. lesspass.min.css:5523:47
Unknown property ‘appearance’.  Declaration dropped. lesspass.min.css:5540:16
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. lesspass.min.css:5554:17
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. lesspass.min.css:5566:21
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. lesspass.min.css:5568:19
Unknown pseudo-class or pseudo-element ‘-ms-track’.  Ruleset ignored due to bad selector. lesspass.min.css:5570:17
Unknown pseudo-class or pseudo-element ‘-ms-fill-lower’.  Ruleset ignored due to bad selector. lesspass.min.css:5578:17
Unknown pseudo-class or pseudo-element ‘-ms-fill-upper’.  Ruleset ignored due to bad selector. lesspass.min.css:5581:17
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. lesspass.min.css:5593:26
Unknown property ‘orphans’.  Declaration dropped. lesspass.min.css:6075:13
Unknown property ‘widows’.  Declaration dropped. lesspass.min.css:6076:12
Unknown property ‘appearance’.  Declaration dropped. lesspass.min.css:6637:14
Stylesheets without CSSOM changes reparsed to check for errors. Refresh the page to also see errors from stylesheets changed from CSSOM and from style attributes.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/user/lesspass/packages/lesspass-pure/dist/af7ae505a9eed503f8b8e6982036873e.woff2. (Reason: CORS request not http).

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:1): bad URI or cross-site access not allowed source: file:///home/user/lesspass/packages/lesspass-pure/dist/af7ae505a9eed503f8b8e6982036873e.woff2 unknown:7:11
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/user/lesspass/packages/lesspass-pure/dist/fee66e712a8a08eef5805a46892932ad.woff. (Reason: CORS request not http).

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:2): bad URI or cross-site access not allowed source: file:///home/user/lesspass/packages/lesspass-pure/dist/fee66e712a8a08eef5805a46892932ad.woff unknown:7:11
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/user/lesspass/packages/lesspass-pure/dist/b06871f281fee6b241d60582ae9369b9.ttf. (Reason: CORS request not http).

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:3): bad URI or cross-site access not allowed source: file:///home/user/lesspass/packages/lesspass-pure/dist/b06871f281fee6b241d60582ae9369b9.ttf unknown:7:11
downloadable font: no supported format found (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:5) source: (end of source list) unknown:7:11​
```
Screenshot_2019-04-16 LessPass

**Comment by Kcchouette** [comment]
In the case the page is in lesspass-pure (and not in src):
```
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. lesspass.min.css:20:27
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. lesspass.min.css:2346:13
Unknown property ‘-moz-opacity’.  Declaration dropped. lesspass.min.css:2348:18
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. lesspass.min.css:2375:13
Unknown property ‘-moz-opacity’.  Declaration dropped. lesspass.min.css:2377:18
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. lesspass.min.css:2390:13
Unknown property ‘-moz-opacity’.  Declaration dropped. lesspass.min.css:2392:18
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. lesspass.min.css:2820:29
Unknown property ‘text-decoration-skip-ink’.  Declaration dropped. lesspass.min.css:2858:28
Error in parsing value for ‘outline’.  Declaration dropped. lesspass.min.css:2969:20
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. lesspass.min.css:4050:17
Unknown pseudo-class or pseudo-element ‘-ms-value’.  Ruleset ignored due to bad selector. lesspass.min.css:4066:27
Unknown property ‘user-select’.  Declaration dropped. lesspass.min.css:4417:15
Unknown property ‘appearance’.  Declaration dropped. lesspass.min.css:5409:14
Unknown pseudo-class or pseudo-element ‘-ms-value’.  Ruleset ignored due to bad selector. lesspass.min.css:5414:26
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. lesspass.min.css:5424:18
Unknown property ‘appearance’.  Declaration dropped. lesspass.min.css:5500:14
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. lesspass.min.css:5507:25
Unknown property ‘appearance’.  Declaration dropped. lesspass.min.css:5519:16
Unknown pseudo-class or pseudo-element ‘active’.  Ruleset ignored due to bad selector. lesspass.min.css:5523:47
Unknown property ‘appearance’.  Declaration dropped. lesspass.min.css:5540:16
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. lesspass.min.css:5554:17
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. lesspass.min.css:5566:21
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. lesspass.min.css:5568:19
Unknown pseudo-class or pseudo-element ‘-ms-track’.  Ruleset ignored due to bad selector. lesspass.min.css:5570:17
Unknown pseudo-class or pseudo-element ‘-ms-fill-lower’.  Ruleset ignored due to bad selector. lesspass.min.css:5578:17
Unknown pseudo-class or pseudo-element ‘-ms-fill-upper’.  Ruleset ignored due to bad selector. lesspass.min.css:5581:17
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. lesspass.min.css:5593:26
Unknown property ‘orphans’.  Declaration dropped. lesspass.min.css:6075:13
Unknown property ‘widows’.  Declaration dropped. lesspass.min.css:6076:12
Unknown property ‘appearance’.  Declaration dropped. lesspass.min.css:6637:14
​```

![Screenshot_2019-04-16 LessPass(1)](https://user-images.githubusercontent.com/3000936/56232590-6e5ac180-6081-11e9-9fa2-5b049a1e8275.png)

**Comment by Kcchouette** [comment]
Screenshot_2019-04-16 LessPass(1)

**Comment by guillaumevincent** [comment]
Hello,
in this case you only need to build it and run it from dist folder.

```
cd packages/lesspass-pure
npm install
npm run build
cd dist
firefox index.html
```

**Pull request closed without merging**
